import { mkdir, readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const source = new URL("../../docs/02-api/openapi.yaml", import.meta.url);
const output = new URL("../../apps/web/src/api/schema.d.ts", import.meta.url);
const generated = `// Generated by tools/openapi-client. Do not edit.\n${astToString(await openapiTS(source))}`;
if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current.replaceAll("\r\n", "\n") !== generated) {
    console.error("Typy API nieaktualne. Uruchom pnpm gen:api-client.");
    process.exitCode = 1;
  } else console.log("Typy klienta API: aktualne.");
} else {
  await mkdir(new URL("./", output), { recursive: true });
  await writeFile(output, generated);
  console.log("Zapisano apps/web/src/api/schema.d.ts.");
}
